export interface IncomingStockRecord {
  id: number;
  date: string;
  siId: string;
  supplier: string;
  warehouse: string;
  supplierRef: string;
  product: string;
  status: "Recorded" | "Draft" | "Reversed";
  createdTime: string;
  addedBy: string;
  action: string;
  // Detail-page extras
  recordedBy: string;
  dateReceived: string;
  products: Array<{ id: number; product: string; productCode: string; quantity: number }>;
  notes?: string;
  reversalReason?: string;
  dateReversed?: string;
  reversedBy?: string;
}

export const incomingStockData: IncomingStockRecord[] = [
  {
    id: 1,
    date: "02 Jan 2026",
    siId: "SI-000001",
    supplier: "Austin Traders",
    warehouse: "Femtech",
    supplierRef: "REF-1001",
    product: "Shred Belly",
    status: "Recorded",
    createdTime: "09:15am",
    addedBy: "Yusuf Adeyemi",
    action: "Created",
    recordedBy: "Yusuf Adeyemi",
    dateReceived: "02-01-2026",
    products: [{ id: 1, product: "Shred Belly", productCode: "SB-001", quantity: 200 }],
  },
  {
    id: 2,
    date: "05 Jan 2026",
    siId: "SI-000002",
    supplier: "Global Supplies",
    warehouse: "Pamtech",
    supplierRef: "REF-1002",
    product: "Slim Tea",
    status: "Draft",
    createdTime: "11:30am",
    addedBy: "Amaka Okafor",
    action: "Created",
    recordedBy: "Amaka Okafor",
    dateReceived: "05-01-2026",
    products: [{ id: 1, product: "Slim Tea", productCode: "ST-002", quantity: 150 }],
    notes: "Pending supplier confirmation",
  },
  {
    id: 3,
    date: "10 Jan 2026",
    siId: "SI-000003",
    supplier: "Zenith Pharma",
    warehouse: "Femtech",
    supplierRef: "ZP-20260110",
    product: "Detox Plus",
    status: "Recorded",
    createdTime: "02:45pm",
    addedBy: "Emeka Nwosu",
    action: "Created",
    recordedBy: "Emeka Nwosu",
    dateReceived: "10-01-2026",
    products: [
      { id: 1, product: "Detox Plus", productCode: "DP-003", quantity: 80 },
      { id: 2, product: "Detox Lite", productCode: "DL-003B", quantity: 40 },
    ],
  },
  {
    id: 4,
    date: "14 Jan 2026",
    siId: "SI-000004",
    supplier: "Lagos Imports Ltd",
    warehouse: "Pamtech",
    supplierRef: "LI-4401",
    product: "Green Coffee",
    status: "Recorded",
    createdTime: "08:00am",
    addedBy: "Fatima Bello",
    action: "Created",
    recordedBy: "Fatima Bello",
    dateReceived: "14-01-2026",
    products: [{ id: 1, product: "Green Coffee", productCode: "GC-004", quantity: 300 }],
  },
  {
    id: 5,
    date: "18 Jan 2026",
    siId: "SI-000005",
    supplier: "MedaFreight Co.",
    warehouse: "Femtech",
    supplierRef: "MF-9912",
    product: "Collagen Boost",
    status: "Draft",
    createdTime: "04:10pm",
    addedBy: "Chidi Obi",
    action: "Created",
    recordedBy: "Chidi Obi",
    dateReceived: "18-01-2026",
    products: [{ id: 1, product: "Collagen Boost", productCode: "CB-005", quantity: 60 }],
    notes: "Partial delivery — awaiting balance",
  },
  {
    id: 6,
    date: "22 Jan 2026",
    siId: "SI-000006",
    supplier: "Nutrimax Inc.",
    warehouse: "Pamtech",
    supplierRef: "NM-6600",
    product: "Fiber Mix",
    status: "Recorded",
    createdTime: "10:00am",
    addedBy: "Yusuf Adeyemi",
    action: "Created",
    recordedBy: "Yusuf Adeyemi",
    dateReceived: "22-01-2026",
    products: [{ id: 1, product: "Fiber Mix", productCode: "FM-006", quantity: 120 }],
  },
  {
    id: 7,
    date: "27 Jan 2026",
    siId: "SI-000007",
    supplier: "Sunrise Distributors",
    warehouse: "Femtech",
    supplierRef: "SD-7711",
    product: "Vitamin C+",
    status: "Recorded",
    createdTime: "01:20pm",
    addedBy: "Amaka Okafor",
    action: "Created",
    recordedBy: "Amaka Okafor",
    dateReceived: "27-01-2026",
    products: [
      { id: 1, product: "Vitamin C+", productCode: "VC-007", quantity: 500 },
      { id: 2, product: "Vitamin D3", productCode: "VD-007B", quantity: 200 },
    ],
  },
  {
    id: 8,
    date: "03 Feb 2026",
    siId: "SI-000008",
    supplier: "Austin Traders",
    warehouse: "Pamtech",
    supplierRef: "REF-1008",
    product: "Omega 3",
    status: "Recorded",
    createdTime: "09:50am",
    addedBy: "Emeka Nwosu",
    action: "Created",
    recordedBy: "Emeka Nwosu",
    dateReceived: "03-02-2026",
    products: [{ id: 1, product: "Omega 3", productCode: "OM-008", quantity: 250 }],
  },
  {
    id: 9,
    date: "07 Feb 2026",
    siId: "SI-000009",
    supplier: "Zenith Pharma",
    warehouse: "Femtech",
    supplierRef: "ZP-20260207",
    product: "Weight Loss Tea",
    status: "Draft",
    createdTime: "03:00pm",
    addedBy: "Fatima Bello",
    action: "Created",
    recordedBy: "Fatima Bello",
    dateReceived: "07-02-2026",
    products: [{ id: 1, product: "Weight Loss Tea", productCode: "WL-009", quantity: 75 }],
    notes: "Quality check pending",
  },
  {
    id: 10,
    date: "12 Feb 2026",
    siId: "SI-000010",
    supplier: "Global Supplies",
    warehouse: "Pamtech",
    supplierRef: "REF-1010",
    product: "Protein Shake",
    status: "Recorded",
    createdTime: "07:30am",
    addedBy: "Yusuf Adeyemi",
    action: "Created",
    recordedBy: "Yusuf Adeyemi",
    dateReceived: "12-02-2026",
    products: [
      { id: 1, product: "Protein Shake (Vanilla)", productCode: "PS-010A", quantity: 180 },
      { id: 2, product: "Protein Shake (Chocolate)", productCode: "PS-010B", quantity: 180 },
    ],
  },
  {
    id: 11,
    date: "17 Feb 2026",
    siId: "SI-000011",
    supplier: "Lagos Imports Ltd",
    warehouse: "Femtech",
    supplierRef: "LI-4411",
    product: "Garcinia Cambogia",
    status: "Recorded",
    createdTime: "12:15pm",
    addedBy: "Chidi Obi",
    action: "Created",
    recordedBy: "Chidi Obi",
    dateReceived: "17-02-2026",
    products: [{ id: 1, product: "Garcinia Cambogia", productCode: "GC-011", quantity: 400 }],
  },
  {
    id: 12,
    date: "20 Feb 2026",
    siId: "SI-000012",
    supplier: "MedaFreight Co.",
    warehouse: "Pamtech",
    supplierRef: "MF-9920",
    product: "Apple Cider Vinegar",
    status: "Draft",
    createdTime: "05:45pm",
    addedBy: "Amaka Okafor",
    action: "Created",
    recordedBy: "Amaka Okafor",
    dateReceived: "20-02-2026",
    products: [{ id: 1, product: "Apple Cider Vinegar", productCode: "ACV-012", quantity: 90 }],
    notes: "Awaiting warehouse confirmation",
  },
  {
    id: 13,
    date: "24 Feb 2026",
    siId: "SI-000013",
    supplier: "Nutrimax Inc.",
    warehouse: "Femtech",
    supplierRef: "NM-6613",
    product: "Liver Cleanse",
    status: "Recorded",
    createdTime: "10:40am",
    addedBy: "Emeka Nwosu",
    action: "Created",
    recordedBy: "Emeka Nwosu",
    dateReceived: "24-02-2026",
    products: [
      { id: 1, product: "Liver Cleanse Caps", productCode: "LC-013A", quantity: 100 },
      { id: 2, product: "Liver Cleanse Syrup", productCode: "LC-013B", quantity: 50 },
    ],
  },
  {
    id: 14,
    date: "28 Feb 2026",
    siId: "SI-000014",
    supplier: "Sunrise Distributors",
    warehouse: "Pamtech",
    supplierRef: "SD-7714",
    product: "Moringa Extract",
    status: "Recorded",
    createdTime: "02:00pm",
    addedBy: "Yusuf Adeyemi",
    action: "Created",
    recordedBy: "Yusuf Adeyemi",
    dateReceived: "28-02-2026",
    products: [{ id: 1, product: "Moringa Extract", productCode: "ME-014", quantity: 320 }],
  },
];
