/**
 * One-off script to create realistic delivery agents, distributed across
 * the most popular states among the 50 orders generated by
 * prisma/seed-real-orders.ts (Rivers, Enugu, Oyo, Abuja (FCT), Kano, Lagos —
 * weighted by how many of those orders landed in each state).
 *
 * Uses the exact same service the real "Add Agent" admin flow calls
 * (createDeliveryAgentWithUser), so each agent gets a real Agent + User +
 * temp password + agent group chat — indistinguishable from a real signup.
 *
 * Run:  npx tsx prisma/seed-delivery-agents.ts
 */

import { PrismaClient } from "@prisma/client";
import { createDeliveryAgentWithUser } from "../modules/delivery/services/create-delivery-agent.service";

// State -> agent count, weighted by order volume from the seeded orders
// (Rivers 11, Enugu 10, Oyo 9, Abuja (FCT) 8, Kano 7, Lagos 5 orders).
const STATE_ALLOCATION: { state: string; count: number }[] = [
  { state: "Rivers", count: 2 },
  { state: "Enugu", count: 2 },
  { state: "Oyo", count: 2 },
  { state: "Abuja (FCT)", count: 2 },
  { state: "Kano", count: 1 },
  { state: "Lagos", count: 1 },
];

function createClient() {
  const url = process.env.DATABASE_URL ?? "";
  if (url.includes("neon.tech")) {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const { Pool, neonConfig } = require("@neondatabase/serverless");
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const { PrismaNeon } = require("@prisma/adapter-neon");
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    neonConfig.webSocketConstructor = require("ws");
    const pool = new Pool({ connectionString: url });
    return new PrismaClient({ adapter: new PrismaNeon(pool) } as never);
  }
  return new PrismaClient();
}

const prisma = createClient() as PrismaClient;

const pick = <T>(arr: T[]): T => arr[Math.floor(Math.random() * arr.length)];
const randInt = (min: number, max: number) => Math.floor(Math.random() * (max - min + 1)) + min;

const FIRST_NAMES = [
  "Adaeze", "Chinedu", "Funmilayo", "Ibrahim", "Ngozi", "Tunde", "Halima", "Emeka",
  "Bukola", "Yusuf", "Chiamaka", "Segun", "Aisha", "Obinna", "Folake", "Musa",
];
const LAST_NAMES = [
  "Okafor", "Bello", "Adeyemi", "Eze", "Mohammed", "Okonkwo", "Balogun", "Nwosu",
  "Abubakar", "Olawale", "Uche", "Adebayo", "Lawal", "Chukwu", "Suleiman",
];

function makeAgent(state: string) {
  const first = pick(FIRST_NAMES);
  const last = pick(LAST_NAMES);
  const phone = `0${randInt(70, 91)}${randInt(10_000_000, 99_999_999)}`;
  return {
    name: `${first} ${last}`,
    email: `${first.toLowerCase()}.${last.toLowerCase()}${randInt(1, 999)}@gmail.com`,
    phone,
    address: `${randInt(1, 200)} ${last} Road, ${state}`,
    state,
    country: "Nigeria",
    statesCovered: [state],
    picksFromOfficeStock: Math.random() > 0.5,
    deliveryFee: pick([1000, 1200, 1500, 1800, 2000]),
  };
}

async function main() {
  const totalAgents = STATE_ALLOCATION.reduce((s, a) => s + a.count, 0);
  console.log(`Generating ${totalAgents} delivery agents across ${STATE_ALLOCATION.length} states\n`);

  const admin = await prisma.user.findFirst({ where: { role: "ADMIN", isActive: true }, select: { id: true } });
  if (!admin) throw new Error("No active ADMIN user found to attribute agent creation to.");

  const created: { name: string; state: string; email: string; tempPassword: string }[] = [];

  for (const { state, count } of STATE_ALLOCATION) {
    for (let i = 0; i < count; i++) {
      const input = makeAgent(state);
      const result = await createDeliveryAgentWithUser({ ...input, addedById: admin.id });
      created.push({ name: result.name, state, email: result.email, tempPassword: result.tempPassword });
      console.log(`  ✓ ${result.name} (${state}) — ${result.email}`);
    }
  }

  console.log(`\n✓ Done. Created ${created.length} delivery agents.\n`);
  console.log("Login credentials:");
  console.log("-------------------");
  for (const a of created) {
    console.log(`${a.name} | ${a.state} | ${a.email} | ${a.tempPassword}`);
  }
}

main()
  .catch((e) => {
    console.error("Agent generation failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
